# Generated by Django 6.0.4 on 2026-05-15 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='PopularEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='popular_equipment/', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, max_length=255, verbose_name='price')),
            ],
        ),
    ]
