# Generated by Django 6.0.4 on 2026-05-15 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homecontent_delete_banner_delete_popularequipment'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='market_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_at_home', to='market.marketitem'),
        ),
    ]
