# Generated by Django 6.0.4 on 2026-05-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecontent_market_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True, verbose_name='Key/Original Text')),
                ('uz', models.TextField(blank=True, null=True, verbose_name='Uzbek (Latin)')),
                ('uz_cyrl', models.TextField(blank=True, null=True, verbose_name='Uzbek (Cyrillic)')),
                ('ru', models.TextField(blank=True, null=True, verbose_name='Russian')),
                ('en', models.TextField(blank=True, null=True, verbose_name='English')),
                ('tr', models.TextField(blank=True, null=True, verbose_name='Turkish')),
            ],
            options={
                'verbose_name': 'Site Text',
                'verbose_name_plural': 'Site Texts',
            },
        ),
    ]
