# Generated by Django 6.0.4 on 2026-05-15 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='equipment name')),
                ('brand', models.CharField(max_length=255, verbose_name='brand')),
                ('hp', models.PositiveIntegerField(verbose_name='horse power')),
                ('condition', models.CharField(max_length=100, verbose_name='condition')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price')),
                ('is_agreement', models.BooleanField(default=False, verbose_name='agreement')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('location_name', models.CharField(max_length=255, verbose_name='location name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rent_images/')),
                ('rent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rent.rentitem')),
            ],
        ),
        migrations.CreateModel(
            name='RentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('land_area', models.CharField(max_length=100, verbose_name='land area')),
                ('order_date', models.DateTimeField(verbose_name='order date')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rent.rentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
