# Generated by Django 6.0.4 on 2026-05-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='active', max_length=20, verbose_name='status'),
        ),
    ]
