# Generated by Django 4.2.30 on 2026-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rentimage_id_alter_rentorder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
