# Generated by Django 6.0.4 on 2026-05-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
