# Generated by Django 6.0.4 on 2026-05-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_renter',
            field=models.BooleanField(default=False, verbose_name='is renter'),
        ),
    ]
