# Generated by Django 4.2.30 on 2026-05-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_resetpasswordrequest_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfy',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default="O'zbekiston", max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='house_number',
            field=models.CharField(default='Kiritilmagan', max_length=50, verbose_name='house number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='Kiritilmagan', max_length=150, verbose_name='street'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=50, verbose_name='region'),
        ),
    ]
