# Generated by Django 6.0.4 on 2026-05-15 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='market_items/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='marketorder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='active', max_length=20, verbose_name='status'),
        ),
    ]
